"""
Zoom API Client

Handles HTTP requests to Zoom's REST API for creating and managing
meetings, using tokens generated by ZoomTokenGenerator.
"""

import requests
from typing import Optional, Dict, Any
from .token_generator import ZoomTokenGenerator


class ZoomAPIClient:
    """
    Client for Zoom REST API v2.

    Requires an API Key and Secret for Server-to-Server OAuth.
    """

    BASE_URL = "https://api.zoom.us/v2"

    def __init__(self, api_key: str, api_secret: str):
        """
        Initialize the API client.

        Args:
            api_key: Zoom API Key.
            api_secret: Zoom API Secret.
        """
        self.token_generator = ZoomTokenGenerator(api_key, api_secret)
        self._token: Optional[str] = None

    def _get_headers(self) -> Dict[str, str]:
        """Generate authorization headers with a fresh token."""
        self._token = self.token_generator.generate_s2s_token()
        return {
            "Authorization": f"Bearer {self._token}",
            "Content-Type": "application/json"
        }

    def create_meeting(
        self,
        user_id: str,
        topic: str,
        start_time: Optional[str] = None,
        duration: int = 30,
        settings: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Create a Zoom meeting for a user.

        Args:
            user_id: Zoom user ID or email.
            topic: Meeting topic/title.
            start_time: ISO 8601 datetime string (optional).
            duration: Meeting duration in minutes.
            settings: Additional meeting settings.

        Returns:
            API response JSON.
        """
        url = f"{self.BASE_URL}/users/{user_id}/meetings"
        payload = {
            "topic": topic,
            "type": 2,  # Scheduled meeting
            "duration": duration,
            "settings": settings or {}
        }
        if start_time:
            payload["start_time"] = start_time

        response = requests.post(url, headers=self._get_headers(), json=payload)
        response.raise_for_status()
        return response.json()

    def get_meeting(self, meeting_id: str) -> Dict[str, Any]:
        """
        Get details of a specific meeting.

        Args:
            meeting_id: Zoom meeting ID.

        Returns:
            Meeting details JSON.
        """
        url = f"{self.BASE_URL}/meetings/{meeting_id}"
        response = requests.get(url, headers=self._get_headers())
        response.raise_for_status()
        return response.json()

    def delete_meeting(self, meeting_id: str) -> bool:
        """
        Delete a Zoom meeting.

        Args:
            meeting_id: Zoom meeting ID.

        Returns:
            True if successful.
        """
        url = f"{self.BASE_URL}/meetings/{meeting_id}"
        response = requests.delete(url, headers=self._get_headers())
        response.raise_for_status()
        return True
